; PlatformIO Project Configuration File

[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Project name
name = Eighty8

; OTA Upload Configuration
upload_protocol = espota
upload_port = {{ESP32_IP_ADDRESS}}
upload_flags = 
    --port=3232
    --auth=
upload_port_wait_time = 10
upload_speed = 115200
